In [58]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [59]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [60]:
df.shape

(569, 33)

In [61]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [62]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Train Test Split

In [63]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [64]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [65]:
X_train

array([[ 0.55620259,  0.08452414,  0.50587599, ...,  0.5877578 ,
        -0.38412305, -1.14978523],
       [-1.05763925,  1.96365697, -1.05169779, ..., -0.33556054,
        -1.08039593, -0.05043347],
       [ 0.39425998,  0.16006717,  0.43697473, ...,  1.50149784,
         0.49771312,  1.05529639],
       ...,
       [-1.76404406,  1.23891604, -1.77110801, ..., -1.72319869,
        -0.02120723, -0.77173811],
       [ 0.15134607,  1.11615862,  0.11962363, ..., -0.66715239,
        -0.59431864, -0.65171394],
       [-0.61090102, -0.22236941, -0.57952151, ...,  0.00697795,
         0.84256525, -0.00288767]])

In [66]:
y_train

75     M
555    B
392    M
302    M
234    B
      ..
386    B
190    M
568    B
90     B
216    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [67]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [68]:
y_train

array([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

### Numpy arrays to PyTorch tensors

In [69]:
x_train_tensor = torch.tensor(X_train)
x_test_tensor = torch.tensor(X_test)
y_train_tensor = torch.tensor(y_train)
y_test_tensor = torch.tensor(y_test)

In [70]:
x_test_tensor.shape

torch.Size([114, 30])

In [71]:
y_train_tensor.shape

torch.Size([455])

In [80]:
from torch.utils.data import Dataset, DataLoader

class CustomeDataset(Dataset):

    def __init__(self,features,labels):

      self.features = features
      self.labels = labels

    def __len__(self):

      return self.features.shape[0]

    def __getitem__(self, index):

       return self.features[index],self.labels[index]

In [83]:
train_dataset = CustomeDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomeDataset(x_test_tensor, y_test_tensor)

In [84]:
train_dataset[10]

(tensor([ 1.5223, -0.0925,  1.5353,  1.5850,  1.3426,  1.1638,  1.6386,  1.4734,
         -0.0649,  0.3716,  2.4489, -0.1111,  2.0883,  1.9203, -0.3454,  0.3577,
          0.7613,  0.8722, -0.2089,  0.3375,  1.9796,  0.0978,  1.8912,  2.0229,
          0.7333,  1.0684,  1.6809,  1.2871,  0.1381,  0.9040]),
 tensor(1.))

In [85]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

### Defining the model

In [86]:
import torch.nn as nn
import torch
class MyNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

Important Parameter

In [87]:
learning_rate = 0.1
epochs = 25

In [88]:
# create Model
model = MyNN(x_train_tensor.shape[1])

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

Training Pipeline

In [93]:

# Convert input tensors to float to match model's default dtype
x_train_tensor = x_train_tensor.float()
y_train_tensor = y_train_tensor.float()

# define loop
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(x_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()


    # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.13632383942604065
Epoch: 2, Loss: 0.12088380008935928
Epoch: 3, Loss: 0.11070075631141663
Epoch: 4, Loss: 0.10334684699773788
Epoch: 5, Loss: 0.09771813452243805
Epoch: 6, Loss: 0.09323190897703171
Epoch: 7, Loss: 0.08954799175262451
Epoch: 8, Loss: 0.08645272254943848
Epoch: 9, Loss: 0.08380427956581116
Epoch: 10, Loss: 0.08150439709424973
Epoch: 11, Loss: 0.07948248088359833
Epoch: 12, Loss: 0.07768644392490387
Epoch: 13, Loss: 0.07607684284448624
Epoch: 14, Loss: 0.0746232122182846
Epoch: 15, Loss: 0.07330162078142166
Epoch: 16, Loss: 0.07209298014640808
Epoch: 17, Loss: 0.07098186016082764
Epoch: 18, Loss: 0.06995559483766556
Epoch: 19, Loss: 0.06900371611118317
Epoch: 20, Loss: 0.06811749935150146
Epoch: 21, Loss: 0.06728958338499069
Epoch: 22, Loss: 0.06651370972394943
Epoch: 23, Loss: 0.06578454375267029
Epoch: 24, Loss: 0.06509745866060257
Epoch: 25, Loss: 0.06444849073886871

In [90]:
model.linear.weight

Parameter containing:
tensor([[ 0.1858,  0.1277,  0.3193,  0.1007,  0.1835,  0.1940,  0.2927,  0.0994,
          0.0123, -0.1799,  0.2104,  0.0457,  0.3129,  0.2763, -0.0914, -0.0049,
         -0.0046,  0.0322, -0.0607, -0.1103,  0.2535,  0.2570,  0.1518,  0.3873,
          0.1291,  0.2003,  0.1047,  0.3372,  0.0634,  0.1410]],
       requires_grad=True)

In [91]:
model.linear.bias

Parameter containing:
tensor([-0.2539], requires_grad=True)

### Evaluation

In [92]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.8863